apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bps-exim-expelabuhan
  namespace: nextgen
  labels:
    app: smart-crawler
    kind: bps-exim
spec:
  schedule: "0 10 2 * *"
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: smart-crawler
            kind: bps-exim
        spec:
          nodeSelector:
            crawler: bps
          containers:
          - name: bps-exim-expelabuhan
            image: 192.168.202.50/crawler/smart-crawler/bps_exim:0.1.5
            imagePullPolicy: IfNotPresent
            command: ["python", "main.py", "--headless", "--data", "ekspor", "--agr", "pelabuhan", "--s3"]
          restartPolicy: Never