apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bps-exim-imdigit
  namespace: nextgen
  labels:
    app: smart-crawler
    kind: bps-exim
spec:
  schedule: "0 10 1 * *"
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: smart-crawler
            kind: bps-exim
        spec:
          nodeSelector:
            crawler: bps
          containers:
          - name: bps-exim-imdigit
            image: 192.168.202.50/crawler/smart-crawler/bps_exim:0.1.0
            imagePullPolicy: IfNotPresent
            command: ["python", "main.py", "--headless", "--data", "impor", "--agr", "kodehs", "--jenishs", "digit", "--indexhs", "13"]
          restartPolicy: Never