apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bps-exim 
  labels:
    app: smart-crawler
    kind: bps-exim 
    namespace: nextgen
spec:
  schedule: "0 10 1 * *"
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: smart-crawler
            kind: bps-exim 
        spec:
          containers:
          - name: bps-exim-export
            image: 192.168.202.50/crawler/smart-crawler/bps_exim
            command: ["python", "main.py", "--headless", "--data", "ekspor"]
            nodeSelector:
              crawler: bps
          - name: bps-exim-import
            image: 192.168.202.50/crawler/smart-crawler/bps_exim
            command: ["python", "main.py", "--headless", "--data", "impor"]
            nodeSelector:
              crawler: bps
          restartPolicy: Never