apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bps-exim
  namespace: nextgen
  labels:
    app: smart-crawler
    kind: bps-exim
spec:
  schedule: "0 10 1 * *"
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: smart-crawler
            kind: bps-exim
        spec:
          nodeSelector:
            crawler: bps
          containers:
          - name: bps-exim-export
            image: 192.168.202.50/crawler/smart-crawler/bps_exim
            imagePullPolicy: IfNotPresent
            command: ["python", "main.py", "--headless", "--data", "ekspor"]
          - name: bps-exim-import
            image: 192.168.202.50/crawler/smart-crawler/bps_exim
            command: ["python", "main.py", "--headless", "--data", "impor"]
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
